### PR TITLE
feat: support iOS 13 / MiFare tags, support macOS

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira-archive.titaniumsdk.com/MOD-2586
**Packaged module**: [ti.nfc-iphone-4.1.0.zip](https://github.com/tidev/ti.nfc/files/8837217/ti.nfc-iphone-4.1.0.zip)

### CODE REVIEW

**Comment by PietroGranati** [comment]
yup

**Comment by jquick-axway** [comment]
@hansemannn, this does not add MiFare support to the existing `NfcAdapter` object returned by `createNfcAdapter()` which we support on both Android and iOS. Instead, you are adding support via new API `createTagReaderSession()`, right? On Android, we should already get MiFare support for free via the existing `NfcAdapter`.

I think it would be better to stick to the cross-platform API we already got.

The existing `NfcAdapter` type has Android exclusive methods to enable/disable detection like your new `TagReaderSession` type. Unfortunately, these Android methods are not really portable... and neither are the new iOS `restartPolling()` and `invalidate()` methods you've added.

Also, the detect callback you added should support all tag types documented below, not just MiFare.
https://developer.apple.com/documentation/corenfc/nfctag

Android should support the following tag types listed in the link below already.
https://developer.android.com/reference/android/nfc/tech/package-summary

**Comment by hansemannn** [comment]
To get this done for now, I would propose to take the current solution (+ macOS support) and add parity with Android once both native APIs come closer together. Merging the NFC logic of both platforms IMHO was a bad idea because it broke many working parts on both ends, just to have some same-called APIs. Depending on the popularity of this module, I am happy to rewrite it in Swift and do 1:1 parity from the beginning :)

**Comment by m1ga** [comment]
another user on slack reported that this version works fine. So hopefully this get merged soon :smile:

**Comment by geqmedia** [comment]
Tested, detection is working but can't read the content. this is my reply 
[WARN]  {
[WARN]    identifier: Object [TiBlob] {},
[WARN]    stringIdentifier: '0472753A307381',
[WARN]    bubbles: true,
[WARN]    type: 'detect',
[WARN]    source: Object {},
[WARN]    cancelBubble: false
[WARN]  }

**Pull request merged**
